global:
  environment: staging

configMap:
  name: better-backend-app-config

django:
  appName: better-backend-app-django
  host: api-v2.integration-betteropinions.com
  image:
    repository: asia-south1-docker.pkg.dev/bo-stage/bo-main
    tag: latest
  replicas: 1
  resources:
    limits:
      cpu: 1
      memory: 2Gi 
    requests:
      cpu: 2
      memory: 4Gi
