global:
  environment: staging

configMap:
  name: better-backend-app-config

django:
  appName: better-backend-app-django
  host: api-v2.integration-betteropinions.com
  image:
    repository: asia-south1-docker.pkg.dev/bo-stage/bo-main
    tag: latest
  replicas: 2
  resources:
    limits:
      cpu: "1"
      memory: "256Mi" 
    requests:
      cpu: "500m"
      memory: "128Mi"
