global:
  environment: staging

configMap:
  name: better-backend-app-config

django:
  appName: better-backend-app-django
  host: api-v2.integration-betteropinions.com
  image:
    repository: {{ .Values.django.image.repository }}
    tag: {{ .Values.django.image.tag }}
  replicas: 2
  resources:
    limits:
      cpu: 3
      memory: 6Gi 
    requests:
      cpu: 2
      memory: 4Gi
