apiVersion: apps/v1
kind: Deployment
metadata:
  name: better-backend-app-django
  labels:
    app: better-backend-app-django
spec:
  replicas: better-backend-app-django
  selector:
    matchLabels:
      app: better-backend-app-django  # Change 'pod' to 'app' for consistency
  template:
    metadata:
      labels:
        app: better-backend-app-django # Change 'pod' to 'app' for consistency
    spec:
      containers:
        - name: better-backend-app-django
          image: asia-south1-docker.pkg.dev/bo-stage/bo-main:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: better-backend-app-config
          resources:
            requests:
              memory: 4Gi
              cpu: 2
            limits:
              memory: 6Gi
              cpu: 3
          livenessProbe:
            httpGet:
                path: /health/
                port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 5
            successThreshold: 1
          readinessProbe:
            httpGet:
                path: /health/
                port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 5
            successThreshold: 1
