apiVersion: v1
kind: Service
metadata:
  name: better-backend-app-django
  labels:
    app: better-backend-app-django
  annotations:
    cloud.google.com/backend-config: '{"default": "django-backend-config"}'
spec:
  type: ClusterIP      
  selector:
    app: better-backend-app-django
  ports:
    - port: 80
      targetPort: 8000
