name: Build and Deploy to GKE using Helm

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: bo-stage
  CLUSTER_NAME: better-staging
  REGION: asia-south1
  DEPLOYMENT_NAME: better-backend-app-django
  IMAGE_NAME: 17-12-2024_11-48-31
  IMAGE_TAG: latest
  ARTIFACT_REPO: bo-main
  ARTIFACT_REGION: asia-south1
  HELM_RELEASE_NAME: my-helm-release
  HELM_CHART_PATH: ./helm-chart  # Path to Helm chart directory
  CONFIG_MAP_NAME: better-backend-app-config
  TEMPLATE_PATH: ./templates

jobs:
  build-and-deploy:
    name: Build and Deploy to GKE using Helm
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Step 3: Set up gcloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      # Step 4: Install gke-gcloud-auth-plugin
      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      # Step 8: Set up GKE context
      - name: Set up GKE context
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} \
            --region ${{ env.REGION }} \
            --project ${{ env.PROJECT_ID }}

     # Step 6: Create and run test pod
      - name: Run Test Pod on GKE
        run: |
          kubectl run test-pod \
            --image=nginx:latest \
            --restart=Never \
            --namespace=default \
            --timeout=60s

      # Optional: Notify on Deployment Success
      - name: Notify Deployment Success
        if: success()
        run: |
          echo "Helm deployment to GKE was successful!"
