name: Build and Deploy Helm Chart to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: bo-stage
  CLUSTER_NAME: better-staging
  REGION: asia-south1
  HELM_RELEASE_NAME: my-helm-release
  HELM_CHART_PATH: ./helm-chart  # Path where the Helm chart will be created

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Get GKE credentials
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Add Bitnami Helm repo
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo update

    - name: Deploy RabbitMQ
      run: |
        helm upgrade --install rabbitmq-test bitnami/rabbitmq -f values.yml

    - name: Verify deployment
      run: |
        kubectl get pods -l app.kubernetes.io/name=rabbitmq
        kubectl logs $(kubectl get pods -l app.kubernetes.io/name=rabbitmq -o jsonpath="{.items[0].metadata.name}")
